version: '3.4'

services:
  ntp:
    build: .
    restart: always
    container_name: ntp
    ports:
      - "123:123/udp"
    read_only: true
    tmpfs:
      - /etc/chrony:rw,mode=1750
      - /run/chrony:rw,mode=1750
      - /var/lib/chrony:rw,mode=1750
    environment:
      - NTP_SERVERS=time.cloudflare.com
      - LOG_LEVEL=0
    network_mode: bridge
